#elasticsearch:
# host: localhost
# port: 9300

spring:
    data:
        elasticsearch:
#            cluster-name: nini
            cluster-nodes: localhost:9300
#            local: false
            repositories:
                enable: true